
# Node Configuration

#infrastructure_id: '<cluster_name-uuid>'
# cluster_nodes:
#   - name: control-1
#     type: control-plane
#   - name: control-2
#     type: control-plane
#   - name: control-3
#     type: control-plane
#   - name: infra-1
#     type: infra
#   - name: infra-2
#     type: infra
#   - name: infra-3
#     type: infra
#   - name: worker-1
#     type: worker
#   - name: worker-2
#     type: worker
#   - name: worker-3
#     type: worker
# machine_sets:
#   - name: worker
#     type: worker
#     replicas: 3
#   - name: infra
#     type: worker
#     replicas: 3

# Authentication Configuration
idp_providers:
  ## Google SSO Configuration
  # - type: Google
  #   name: RedHatSSO
  #   clientID: "clientID"
  #   clientSecret: "clientSecret"
  #   hostedDomain: "redhat.com" # optional - restricts logins to users with this domain

  # ## LDAP Configuration
  # - type: LDAP
  #   name: LabLDAP
  #   bindDN: "bindDN"
  #   bindPassword: "bindPassword"
  #   cacert: "cacert"
  #   url: "url"
  #   url_filter: "url_filter"
  #   # mappingMethod: claim # optional, defaults to claim
  #   # insecure: false # optional, defaults to false
  #   group_sync:
  #     group_crbs:
  #       - group: admins
  #         crb: cluster-admin
  #       - group: labadmins
  #         crb: cluster-admin
  #     groupBaseDN: "groupBaseDN"
  #     groupFilter: (|(cn=labadmins)(cn=admins))
  #     userBaseDN: "userBaseDN"
  #     groupUIDNameMappings:
  #       - ldapGroup: cn=labadmins,groupBaseDN
  #         openshiftGroup: labadmins
  #       - ldapGroup: cn=admins,groupBaseDN
  #         openshiftGroup: admins

## Active Directory Configuration

  #  - type: ActiveDirectory
  #    name: Corp AD
  #    mappingMethod: claim
  #    bindDN: "ad-svc-acct-name"
  #    bindPassword: "{{ lookup('file', '/home/kemo/.idm-bind-pw') }}"
  #    cacert: "{{ lookup('file', '/home/kemo/win-ad-cert.pem') }}"
  #    url: "ldaps://domaincontroller/DC=demo,DC=openshift,DC=pub?sAMAccountName?sub"

# NTP Configuration
#ntp_sources:
#  - type: server
#    address: 192.168.42.14
#  - type: pool
#    address: 0.rhel.pool.ntp.org
